import { PrismaClient } from '@prisma/client'
import { writeFileSync, mkdirSync, existsSync, copyFileSync } from 'fs'
import path from 'path'

const prisma = new PrismaClient()

// 2tワイドロングアルミバンの荷台内寸（mm）
// 佐川・ヤマト等の宅配便で最も使われるサイズ
const TRUCK_2T = {
  name: '2tワイドロング（アルミバン）',
  width: 2000,   // X: 幅
  depth: 4400,   // Y: 奥行き
  height: 2000,  // Z: 高さ
}

// サンプルのボクセルトラック
const SAMPLE_VOXEL_TRUCK = {
  name: 'ボクセルトラック（テスト）',
  // sample/objからコピー
  srcObjPath: path.join(process.cwd(), '..', '..', 'sample', 'obj', 'trunkVoxel_2512131543.obj'),
  srcMtlPath: path.join(process.cwd(), '..', '..', 'sample', 'obj', 'trunkVoxel_2512131543.mtl'),
}

/**
 * 荷台のOBJファイルを生成（Z-up座標系）
 * 入り口は後方（Y=depth側）を開放
 */
function generateTruckCargoObj(width: number, depth: number, height: number): string {
  // mmからmに変換
  const w = width / 1000
  const d = depth / 1000
  const h = height / 1000

  const lines = [
    '# Generated by Hannals - 2t Truck Cargo Area',
    `# Dimensions: ${width}mm x ${depth}mm x ${height}mm`,
    '',
    'o cargo_area',
    '',
    '# 頂点（Z-up座標系: 1-indexed）',
    `v 0 0 0`,           // 1: 左手前下
    `v ${w} 0 0`,        // 2: 右手前下
    `v ${w} ${d} 0`,     // 3: 右奥下
    `v 0 ${d} 0`,        // 4: 左奥下
    `v 0 0 ${h}`,        // 5: 左手前上
    `v ${w} 0 ${h}`,     // 6: 右手前上
    `v ${w} ${d} ${h}`,  // 7: 右奥上
    `v 0 ${d} ${h}`,     // 8: 左奥上
    '',
    '# 面（反時計回りで外向き法線）',
    '# 底面 (Z=0)',
    'f 1 2 3 4',
    '# 前面 (Y=0) - 入り口の反対側',
    'f 1 5 6 2',
    '# 左側面 (X=0)',
    'f 1 4 8 5',
    '# 右側面 (X=width)',
    'f 2 6 7 3',
    '# 天井 (Z=height)',
    'f 5 8 7 6',
    '# 後面は開放（入り口）',
    '',
  ]

  return lines.join('\n')
}

async function main() {
  console.log('Seeding database...')

  // uploadsディレクトリを作成
  const uploadsDir = path.join(process.cwd(), 'uploads')
  if (!existsSync(uploadsDir)) {
    mkdirSync(uploadsDir, { recursive: true })
  }

  // 2tトラックのOBJファイルを生成
  const objContent = generateTruckCargoObj(TRUCK_2T.width, TRUCK_2T.depth, TRUCK_2T.height)
  const objFileName = 'truck_2t_standard.obj'
  const objFilePath = path.join(uploadsDir, objFileName)
  writeFileSync(objFilePath, objContent)
  console.log(`Created OBJ file: ${objFilePath}`)

  // 既存の2tトラックを削除
  await prisma.truck.deleteMany({
    where: { name: TRUCK_2T.name }
  })

  // 2tトラックをDBに登録
  const truck = await prisma.truck.create({
    data: {
      name: TRUCK_2T.name,
      objFilePath: `uploads/${objFileName}`,
      entranceDirection: 'back',
      minX: 0,
      minY: 0,
      minZ: 0,
      maxX: TRUCK_2T.width,
      maxY: TRUCK_2T.depth,
      maxZ: TRUCK_2T.height,
    }
  })

  console.log(`Created truck: ${truck.name} (${truck.id})`)
  console.log(`  Dimensions: ${TRUCK_2T.width}mm x ${TRUCK_2T.depth}mm x ${TRUCK_2T.height}mm`)
  console.log(`  Volume: ${(TRUCK_2T.width * TRUCK_2T.depth * TRUCK_2T.height / 1e9).toFixed(2)} m³`)

  // サンプルのボクセルトラックを追加
  if (existsSync(SAMPLE_VOXEL_TRUCK.srcObjPath)) {
    const voxelObjFileName = 'trunkVoxel_sample.obj'
    const voxelMtlFileName = 'trunkVoxel_sample.mtl'
    const voxelObjFilePath = path.join(uploadsDir, voxelObjFileName)
    const voxelMtlFilePath = path.join(uploadsDir, voxelMtlFileName)

    // ファイルをコピー
    copyFileSync(SAMPLE_VOXEL_TRUCK.srcObjPath, voxelObjFilePath)
    console.log(`Copied OBJ file: ${voxelObjFilePath}`)

    if (existsSync(SAMPLE_VOXEL_TRUCK.srcMtlPath)) {
      copyFileSync(SAMPLE_VOXEL_TRUCK.srcMtlPath, voxelMtlFilePath)
      console.log(`Copied MTL file: ${voxelMtlFilePath}`)
    }

    // 既存のボクセルトラックを削除
    await prisma.truck.deleteMany({
      where: { name: SAMPLE_VOXEL_TRUCK.name }
    })

    // ボクセルトラックをDBに登録
    // 注: サイズは仮の値（実際のOBJから自動検出されるべき）
    const voxelTruck = await prisma.truck.create({
      data: {
        name: SAMPLE_VOXEL_TRUCK.name,
        objFilePath: `uploads/${voxelObjFileName}`,
        mtlFilePath: `uploads/${voxelMtlFileName}`,
        entranceDirection: 'back',
        // サンプルOBJのバウンディングボックス（事前に計算済み）
        // X: -19186.9 to 13813.1, Y: -15597.9 to 9402.1, Z: 0 to 11354.6
        minX: -19186.9,
        minY: -15597.9,
        minZ: 0,
        maxX: 13813.1,
        maxY: 9402.1,
        maxZ: 11354.6,
      }
    })

    console.log(`Created voxel truck: ${voxelTruck.name} (${voxelTruck.id})`)
  } else {
    console.log('Sample voxel truck OBJ not found, skipping...')
  }

  console.log('Seeding completed!')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
